// react-app/src/App.js
import React, { useState, useEffect } from "react";

import "./angular-files/runtime";
import "./angular-files/polyfills";

import "./angular-files/main";
import "./angular-files/styles.css";
import "./App.css";

function App() {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [email, setEmail] = useState("");

  const [angularInputValue, setAngularInputValue] = useState("");

  document.addEventListener(
    "angular-input-event",
    function (e) {
      setAngularInputValue(e.detail);
    },
    { capture: true }
  );

  return (
    <div className="app">
      <div className="react-app">
        <h1>React App</h1>
        <div class="input-group mb-3 mt-3">
          <input
            type="text"
            className="form-control"
            placeholder="First Name"
            aria-label="firstName"
            onChange={(e) => setFirstName(e.target.value)}
            value={firstName}
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            className="form-control"
            placeholder="Last Name"
            aria-label="lastName"
            onChange={(e) => setLastName(e.target.value)}
            value={lastName}
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            className="form-control"
            placeholder="Phone Number"
            aria-label="phoneNumber"
            onChange={(e) => setPhoneNumber(e.target.value)}
            value={phoneNumber}
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <input
            type="text"
            className="form-control"
            placeholder="Email"
            aria-label="email"
            onChange={(e) => setEmail(e.target.value)}
            value={email}
            aria-describedby="basic-addon1"
          />
        </div>
        <div class="input-group mb-3">
          <div className="d-flex flex-row">
            <span className="me-2">Approval Status:</span>
            <span>{angularInputValue}</span>
          </div>
        </div>
      </div>
      <div className="angular-app">
        <h1 className="mb-2">Angular App</h1>
        <angular-component
          first-name={firstName}
          last-name={lastName}
          phone-number={phoneNumber}
          email={email}
        />
      </div>
    </div>
  );
}
export default App;

// angular-app/src/app/app.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-app';
  @Input() firstName = '';
  @Input() lastName = '';
  @Input() phoneNumber = '';
  @Input() email = '';
  inputValue = '';

  changeWebsite(event: any) {
    this.inputValue = event.target.value;
    document.dispatchEvent(
      new CustomEvent('angular-input-event', { detail: event.target.value })
    );
  }
}

<div class="angular-app-container">
  <div class="row-group">
    <h6 class="field-name">First Name</h6>
    <div class="field-value">{{ firstName }}</div>
  </div>
  <div class="row-group">
    <h6 class="field-name">Last Name</h6>
    <div class="field-value">{{ lastName }}</div>
  </div>
  <div class="row-group">
    <h6 class="field-name">Phone Number</h6>
    <div class="field-value">{{ phoneNumber }}</div>
  </div>
  <div class="row-group">
    <h6 class="field-name">Email</h6>
    <div class="field-value">{{ email }}</div>
  </div>
  <select
    formControlName="website"
    class="form-control"
    (change)="changeWebsite($event)"
  >
    <option disabled>Select Status</option>
    <option value="Approved">Approved</option>
    <option value="Rejected">Rejected</option>
  </select>
</div>
